export const products = [
	{
		id: 1,
		name: "Nastar Wisman Premium",
		price: "Rp 145.000",
		rating: 4.9,
		category: "Best Seller",
		image: "/products/nastar.webp",
		desc: "Butter wisman asli dengan selai nanas buatan sendiri.",
		tag: "Terlaris",
	},
	{
		id: 2,
		name: "Kastengel Keju Edam",
		price: "Rp 155.000",
		rating: 4.8,
		category: "Premium",
		image: "/products/kastangel.webp",
		desc: "Gurihnya keju edam melimpah di setiap gigitan.",
		tag: "Baru",
	},
	{
		id: 3,
		name: "Kue Kacang Mete",
		price: "Rp 135.000",
		rating: 4.7,
		category: "Best Seller",
		image: "/products/kacang-mete.webp",
		desc: "Lumer di mulut dengan sensasi kacang mede renyah.",
		tag: "Terlaris",
	},
	{
		id: 4,
		name: "Choco Chips",
		price: "Rp 125.000",
		rating: 4.5,
		category: "Best Seller",
		image: "/products/choco-chips.webp",
		desc: "Manisnya coklat dalam setiap gigitan",
		tag: "Terlaris",
	},
	{
		id: 5,
		name: "Kembang Goyang Harum",
		price: "Rp 100.000",
		rating: 4.8,
		category: "Best Seller",
		image: "/products/kembang-goyang.webp",
		desc: "Renyah dan manis dalam tiap kerenyahan.",
		tag: null,
	},
	{
		id: 6,
		name: "Kue Batang Cokelat",
		price: "Rp 135.000",
		rating: 4.7,
		category: "Premium",
		image: "/products/kering-cokelat-batang.webp",
		desc: "Renyah dan manisnya cokelat dalam satu gigitan.",
		tag: "Terlaris",
	},
	{
		id: 7,
		name: "Kuping Gajah",
		price: "Rp 90.000",
		rating: 4.7,
		category: "Best Seller",
		image: "/products/kuping-gajah.webp",
		desc: "Renyah dan manis",
		tag: "Terlaris",
	},
	{
		id: 8,
		name: "Tumbrint Cokelat",
		price: "Rp 150.000",
		rating: 4.7,
		category: "Premium",
		image: "/products/tumbrint-cokelat.webp",
		desc: "Sensasi manisnya cokelat premium.",
		tag: null,
	},
	{
		id: 9,
		name: "Hampers Berkah 1",
		price: "Rp 400.000",
		rating: 4.7,
		category: "Hampers",
		image: "/hampers/hampers2.webp",
		desc: "Paket Hemat: Nastar, Kastengel, Tumbrint Cokelat.",
		tag: "Promo",
	},
	{
		id: 10,
		name: "Hampers Berkah 2",
		price: "Rp 400.000",
		rating: 4.7,
		category: "Hampers",
		image: "/hampers/hampers3.webp",
		desc: "Paket Hemat: Nastar, Choco Chips, Kastangel",
		tag: "Promo",
	},
];
