export const products = [
	{
		id: 1,
		name: "Nastar Wisman Premium",
		price: 145000,
		rating: 4.9,
		category: "Best Seller",
		image: "/products/nastar.webp",
		desc: "Butter wisman asli dengan selai nanas buatan sendiri.",
		tag: "Terlaris",
	},
	{
		id: 2,
		name: "Kastengel Keju Edam",
		price: 155000,
		rating: 4.8,
		category: "Premium",
		image: "/products/kastangel.webp",
		desc: "Gurihnya keju edam melimpah di setiap gigitan.",
		tag: "Baru",
	},
	{
		id: 3,
		name: "Kue Kacang Mete",
		price: 135000,
		rating: 4.7,
		category: "Best Seller",
		image: "/products/kacang-mete.webp",
		desc: "Lumer di mulut dengan sensasi kacang mede renyah.",
		tag: "Terlaris",
	},
	{
		id: 4,
		name: "Choco Chips",
		price: 125000,
		rating: 4.5,
		category: "Best Seller",
		image: "/products/choco-chips.webp",
		desc: "Manisnya coklat dalam setiap gigitan",
		tag: "Terlaris",
	},
	{
		id: 5,
		name: "Kembang Goyang Harum",
		price: 100000,
		rating: 4.8,
		category: "Best Seller",
		image: "/products/kembang-goyang.webp",
		desc: "Renyah dan manis dalam tiap kerenyahan.",
		tag: null,
	},
	{
		id: 6,
		name: "Kue Batang Cokelat",
		price: 135000,
		rating: 4.7,
		category: "Premium",
		image: "/products/kering-cokelat-batang.webp",
		desc: "Renyah dan manisnya cokelat dalam satu gigitan.",
		tag: "Terlaris",
	},
	{
		id: 7,
		name: "Kuping Gajah",
		price: 90000,
		rating: 4.7,
		category: "Best Seller",
		image: "/products/kuping-gajah.webp",
		desc: "Renyah dan manis",
		tag: "Terlaris",
	},
	{
		id: 8,
		name: "Tumbrint Cokelat",
		price: 150000,
		rating: 4.7,
		category: "Premium",
		image: "/products/tumbrint-cokelat.webp",
		desc: "Sensasi manisnya cokelat premium.",
		tag: null,
	},
	{
		id: 9,
		name: "Hampers Berkah 1",
		price: 400000,
		rating: 4.7,
		category: "Hampers",
		image: "/hampers/hampers2.webp",
		desc: "Paket Hemat: Nastar, Kastengel, Tumbrint Cokelat.",
		tag: "Promo",
	},
	{
		id: 10,
		name: "Hampers Berkah 2",
		price: 400000,
		rating: 4.7,
		category: "Hampers",
		image: "/hampers/hampers3.webp",
		desc: "Paket Hemat: Nastar, Choco Chips, Kastangel",
		tag: "Promo",
	},
];
